### ISSUE TITLE
Fetch Request

### ISSUE THREAD

**Issue by demkoa01** [brandonespencer/Food-and-a-Flick#9]
- Setup Fetch request 
- Food: Recipe & nutritional  information
- Email API 

BACKUP:
- Movie API to randomly show movies for user to watch while they eat/cook

**Comment by Mike2481** [comment]
Movie API fetch completed. Still need fetch for recipe and nutritional information

**Comment by Mike2481** [comment]
food API and Movie API are done and generating good data/elements
